### ISSUE TITLE
Install incompatible with latest Python versions - ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by jamesbrayton** [ExtensityAI/symbolicai#48]
When attempting a fresh install of symbolic AI using latest Python 3.12, an exception happens during the pip installation stating: 
`ModuleNotFoundError: No module named 'distutils'`

As far as I am aware, distutils started being phased out in 3.10 and has been completely removed by 3.12.  A few solutions of similar problems suggest trying to install `setup-tools` but that did not work in my case, and beyond that, the general consensus is for developers to update their solutions to not rely on `distutils`.

**Comment by jamesbrayton** [comment]
Fought with this a bit more this morning - I think this is actual and issue with setuptools and not symbolicai.  If someone else is able to replicate and/or confirm I'm happy to close or withdraw this issue.

**Comment by Xpitfire** [comment]
Hi there, 
thank you for reaching out and also great that you gave it another try.
I looked at reproducing the issue today and actually encountered another issue with Python 3.12 and PyTorch on a MacOS (Apple Silicon) machine, since it does not find a compatible torch>=2.0.0 version. However, I could not reproduce the `distutils` issue so far. Tested it on several versions of Python, including MacOS Sonoma, several linux distributions, including the current docker image build with Ubuntu Linux 20.04.6 LTS, Python 3.10.11 and PyTorch 2.0.1 and Windows 11 versions.
 What machine are you operating on?
