### ISSUE TITLE
Causal Reasoning Expressions Not working 

### ISSUE THREAD

**Issue by abd-als** [ExtensityAI/symbolicai#71]
Im trying to use the expressions interpret and expression but it doesnt seem to work.

```
res = ai.Symbol('The horn only sounds on Sundays.') & ai.Symbol('I hear the horn.')
res
;class symai.symbol.Symbol at 0x11a6d7a10>(value=The horn only sounds on Sundays.I hear the horn.)
```

The actual output should be : <class 'symai.expressions.Symbol'>(value=It is Sunday.)

What I get is "(value=The horn only sounds on Sundays.I hear the horn.)" which just adds them together the Reasoning part is not working.

**Comment by futurisold** [comment]
Hey! Sorry for the late reply. There was a subtle bug, which we fixed in the meantime. Please pull latest `main` and use as follows: 
```python
from symai import Symbol

s1 = Symbol('The horn only sounds on Sundays.', only_nesy=True)
s2 = Symbol('I hear the horn.')

print(s1 & s2) # or |
```

The first symbol (in the above case that's `s1`) must have the `only_nesy` flag set to `True` for the logical operators. Without going into detail for why we did this, the tl'dr is that we didn't find a better way in python to do meta-overloading. Without this flag, the logical operators default to string concatenation. For us, having syntactic sugar for concatenation is important, such as being able to use operators like `'A' & 'B' & 'C'` to produce `'ABC'` or `'A' | 'B' | 'C'` to result in `'A B C '`.

Please confirm it's working on your end as well.

**Comment by futurisold** [comment]
Due to innactivity.

**Comment by abd-als** [comment]
![Screenshot 2024-09-16 at 8 40 11 PM (2)](https://github.com/user-attachments/assets/9f12a475-91b8-4ee9-95c4-596de9cafc76)


hello, It still gives out the same output

**Comment by futurisold** [comment]
I'm not sure what's the issue. It could be that the jupyter state messes something up. 

On my machine on latest main:
![image](https://github.com/user-attachments/assets/9cb4e5f2-96c0-4cdc-94e9-0429bf2d369f)
